apiVersion: apps/v1
kind: Deployment
metadata: 
  name: the-deployment 
spec:   
  template: 
    spec: 
      containers: 
        - name: the-container
          env: 
            - name: CUSTOM_ENV_VAR
              value: Value Defined by Kustomize 
