apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- custom-env.yaml
- replica-rollout.yaml
resources:
- ../../base
secretGenerator:
- literals:
  - db-password=12345
  name: demo-app
  type: Opaque
